<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5375 2010-09-10 02:48:01Z huuphuoc $
 * @since		2.0.9
 */
?>
<?php if ($this->page) : ?>
<div class="t_page_page">
    <h2><?php echo $this->page->name; ?></h2>
    <div class="description">
    	<?php echo $this->page->description; ?>
    </div>
    <div class="more">
    	<a href="<?php echo $this->url($this->page->getProperties(), 'page_page_details'); ?>"><?php echo $this->translator()->widget('details'); ?></a>
    </div>
</div>
<?php endif; ?>
