<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: _icons.phtml 5125 2010-08-30 04:05:28Z huuphuoc $
 * @since		2.0.3
 */
?>
<?php if (stripos($this->icons, 'image') == true) : ?>
<span class="t_news_image">&nbsp;</span>
<?php endif; ?>

<?php if (stripos($this->icons, 'video') == true) : ?>
<span class="t_news_video">&nbsp;</span>
<?php endif; ?>
