<?php
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 3556 2010-07-11 08:14:50Z huuphuoc $
 * @since		2.0.7
 */
?>

<div class="t_a_ui_dashboard_widget">
	<div class="t_a_ui_dashboard_widget_head">
		<h3><?php echo $this->translator()->widget('title'); ?></h3>
	</div>
	<div class="t_a_ui_dashboard_widget_content">
		<?php if (0 == count($this->sites)) : ?>
		<div class="t_a_bottom"><?php echo $this->translator()->widget('not_found'); ?></div>
		<?php else : ?>
		<div class="t_a_bottom"><?php echo $this->translator()->widget('guide'); ?></div>
		
		<?php foreach ($this->sites as $site) : ?>
		<hr />
		<div class="t_a_bottom">
			<?php echo $site['title']; ?><br />
			<a href="<?php echo $site['url']; ?>"><?php echo $site['displayUrl']; ?></a>
		</div>
		<?php endforeach; ?>
		<?php endif; ?>
	</div>
</div>
