<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5387 2010-09-11 01:30:11Z huuphuoc $
 * @since		2.0.9
 */
?>
<div class="t_seo_gatracker">
	<h2><?php echo $this->translator()->widget('title'); ?></h2>

	<div><?php echo $this->translator()->widget('statistic_days'); ?></div>
	
	<ul>
		<li><?php echo sprintf($this->translator()->widget('visitors'), $this->counter['visitors']); ?></li>
		<li><?php echo sprintf($this->translator()->widget('visits'), $this->counter['visits']); ?></li>
		<li><?php echo sprintf($this->translator()->widget('pageviews'), $this->counter['pageviews']); ?></li>
	</ul>
	
	<div class="poweredby"><a href="http://www.google.com/analytics/"><?php echo $this->translator()->widget('powered_by'); ?></a></div>
</div>
