<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 4783 2010-08-23 10:41:16Z huuphuoc $
 * @since		2.0.6
 */
?>
<?php 
$this->headTitle($this->translator('cache_config_title'));
?>

<div class="grid_12 t_a_ui_breadcrumb">
	<span><a href="<?php echo $this->url(array(), 'core_cache_list'); ?>"><?php echo $this->translator('cache_list_breadcrumb'); ?></a></span>	
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array(), 'core_cache_config'); ?>">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('cache_config_page_guide'); ?></div>

<!-- Cache entire pages -->
<div class="grid_12 t_a_ui_data_list_header">
	<div class="grid_8 alpha">
		<div><?php echo $this->translator('cache_config_page'); ?></div>
	</div>
	
	<div class="grid_4 omega"><?php echo $this->translator('cache_config_lifetime'); ?></div>
</div>

<div class="grid_12 t_a_bottom">
	<?php foreach ($this->pages as $page) : ?>
	<div class="clearfix t_a_ui_data_list_content">
		<div class="grid_8 alpha">
			<div>
				<input type="checkbox" name="selectedPages[]" value="<?php echo $page['page']->route; ?>" <?php if ($page['cache']['enable'] == 'true') : ?>checked="checked" <?php endif; ?>/> <?php echo $page['page']->title; ?>
			</div>
		</div>
		
		<div class="grid_4 omega">
			<input type="text" name="lifetime[<?php echo $page['page']->route; ?>]" value="<?php echo $page['cache']['lifetime']; ?>" <?php if ($page['cache']['enable'] != 'true') : ?>disabled="disabled" <?php endif; ?>style="width: 100px" />
		</div>
	</div>
	<?php endforeach; ?>
</div>

<!-- Compress configurations -->
<div class="grid_12 t_a_bottom"><?php echo $this->translator('cache_config_compress_guide'); ?></div>

<div class="grid_12 t_a_ui_data_list_header">
	<div class="alpha">
		<div><?php echo $this->translator('cache_config_compress'); ?></div>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<div class="t_a_ui_data_list_content">
		<input type="checkbox" name="compressCss" value="1" <?php if ($this->compressCss == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_css'); ?>
	</div>
	<div class="t_a_ui_data_list_content">
		<input type="checkbox" name="compressJs" value="1" <?php if ($this->compressJs == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_javascript'); ?>
	</div>
	<div class="t_a_ui_data_list_content">
		<input type="checkbox" name="compressHtml" value="1" <?php if ($this->compressHtml == 'true') : ?> checked="checked"<?php endif; ?>/> <?php echo $this->translator('cache_config_compress_html'); ?>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<button type="submit"><span><?php echo $this->translator('cache_config_save'); ?></span></button>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('input[name="selectedPages[]"]').change(function() {
		var pageName = $(this).val();
		var lifetimeInput = $(this).parents('.t_a_ui_data_list_content').find('input[name="lifetime[' + pageName + ']"]:first');
		if ($(this).attr('checked') == 'checked' || $(this).attr('checked') == true) {
			$(lifetimeInput).removeAttr('disabled').focus();
		} else {
			$(lifetimeInput).attr('disabled', 'disabled');
		}
	});
});
</script>
