<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5432 2010-09-14 09:32:52Z huuphuoc $
 * @since		2.0.0
 */
?>
<div class="t_utility_twitter">
	<h2><?php echo sprintf($this->translator()->widget('title'), '"http://twitter.com/' . $this->account . '/"'); ?></h2>
	<?php if (count($this->items) > 0) : ?>
	<ul>
		<?php foreach ($this->items as $item) : ?>
		<li>
			<?php echo $this->helper()->format($item['text']); ?>
			<cite><?php echo $this->dateFormatter()->diff(strtotime(substr($item['created_at'], 0, 10) . substr($item['created_at'], 25, 5) . substr($item['created_at'], 10, 15)), $this->dateFormat); ?></cite>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php endif; ?>
</div>
