<div class="t_a_bottom">
	<div class="t_a_ui_helper_line">
		<h3>Internal Links</h3>
	</div>
	<div>
		<div class="t_a_bottom">
			Click on the link below to insert it to the content editor:
		</div>
		<div class="t_a_bottom">
			<?php echo $this->linkProvider(array('jsCallback' => 'insertLinkToEditor')); ?>
		</div>
	</div>
</div>
<script type="text/javascript">
function insertLinkToEditor(route, href, title) {
	tinyMCE.getInstanceById('content').execCommand('mceInsertContent', false, '<a href="' + href + '">' + title + '</a>');
};
</script>
