<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5116 2010-08-30 03:16:31Z huuphuoc $
 * @since		2.0.0
 */
?>
<div class="t_news_newest">
	<?php if ($this->articles) : ?>
	<ul>
		<?php foreach ($this->articles as $article) : ?>
		<li class="clearfix">
			<?php if ($article->image_square) : ?>
			<div class="image">
				<a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img src="<?php echo $article->image_square; ?>" /></a>
			</div>
			<?php endif; ?>
			
			<h2><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></h2>
			<cite><?php echo $this->dateFormatter()->diff(strtotime($article->created_date), $this->dateFormat); ?></cite>
		</li>
		<?php endforeach; ?>
	</ul>
	<?php endif; ?>
</div>
