<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5373 2010-09-10 02:22:07Z huuphuoc $
 * @since		2.0.9
 */
?>
<?php if ($this->links) : ?>
<div class="t_utility_links">
	<h2><?php echo $this->title; ?></h2>
	
	<ul>
	<?php foreach ($this->links as $link) : ?>
		<li><a href="<?php echo $link['url']; ?>"><?php echo $link['label']; ?></a></li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
