<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5116 2010-08-30 03:16:31Z huuphuoc $
 * @since		2.0.0
 */
?>
<?php if ($this->categories) : ?>
<div class="t_news_breadcrumb">
	<h2>
		<span><a href="<?php echo $this->baseUrl(); ?><?php echo $this->lang; ?>"><?php echo $this->translator()->widget('home'); ?></a></span>
		
		<?php foreach ($this->categories as $index => $category) : ?>
		/ <span><a href="<?php echo $this->url($category->getProperties(), 'news_article_category'); ?>"><?php echo $category->name; ?></a></span>
		<?php endforeach; ?>
	</h2>
</div>
<?php endif; ?>
