<?php
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: load.phtml 5231 2010-08-31 04:45:59Z huuphuoc $
 * @since		2.0.8
 */
?>
<?php if (($articles = $this->helper()->getLatestArticles($this->category, $this->limit)) != null && count($articles) > 0) : ?>
<div class="grid_3 alpha">
	<?php if ($articles[0]->image_small) : ?>
	<div class="image">
		<a href="<?php echo $this->url($articles[0]->getProperties(), 'news_article_details'); ?>">
			<img src="<?php echo $articles[0]->image_small; ?>" />
		</a>
	</div>
	<?php endif; ?>
	
	<h3>
		<a href="<?php echo $this->url($articles[0]->getProperties(), 'news_article_details'); ?>">
			<?php echo $this->articleIcons($articles[0]->icons); ?> <?php echo $articles[0]->title; ?>
		</a>
		<cite><?php echo $this->dateFormatter()->diff(strtotime($articles[0]->created_date), $this->dateFormat); ?></cite>
	</h3>
</div>

<div class="grid_5 omega">
	<ul>
	<?php for ($i = 1; $i < count($articles); $i++) : ?>
		<li>
			<?php echo $this->articleIcons($articles[$i]->icons); ?><a href="<?php echo $this->url($articles[$i]->getProperties(), 'news_article_details'); ?>"><?php echo $articles[$i]->title; ?></a>
			<cite><?php echo $this->dateFormatter()->diff(strtotime($articles[$i]->created_date), $this->dateFormat); ?></cite>
		</li>
	<?php endfor; ?>
	</ul>
	
	<div class="more">
		<a href="<?php echo $this->url($this->category->getProperties(), 'news_article_category'); ?>"><?php echo $this->translator()->widget('read_more'); ?></a>
	</div>
</div>

<div class="clear"></div>
<?php endif; ?>
