<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5386 2010-09-11 01:29:30Z huuphuoc $
 * @since		2.0.0
 */
?>
<?php if ($this->files != null && count($this->files) > 0) : ?>
<div class="t_multimeida_player">
   	<h2><?php echo $this->translator()->widget('title'); ?></h2>
   		    					    				    	
	<ul>
	<?php foreach ($this->files as $file) : ?>
		<li>
			<a href="<?php echo $this->url($file->getProperties(), 'multimedia_file_details'); ?>">
				<span><?php echo $file->title; ?></span>
				<img src="<?php echo $file->image_small; ?>" />
			</a>
			<div></div>
		</li>
	<?php endforeach; ?>
	</ul>
	
	<div class="clearfix"></div>
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function() {	
	$('.t_multimeida_player li').mouseenter(function(e) {
        $(this).children('a').children('img').animate(100);
        $(this).children('a').children('span').fadeIn(200);
    }).mouseleave(function(e) {
        $(this).children('a').children('img').animate(100);
        $(this).children('a').children('span').fadeOut(200);
    });
});
<?php $this->headScript()->captureEnd(); ?>
<?php endif; ?>
