<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5114 2010-08-30 03:03:37Z huuphuoc $
 * @since		2.0.3
 */
?>
<div class="t_utility_flickr">
   	<h2><?php echo $this->translator()->widget('title'); ?></h2>
   	
    <?php if ($this->resultSet) : ?>
    <ul>
    	<?php foreach ($this->resultSet as $result) : ?>
    	<li>
    		<a href="<?php echo $result->Square->clickUri; ?>" title="<?php echo $this->escape($result->title); ?>">
    			<img src="<?php echo $result->Square->uri; ?>" alt="<?php echo $this->escape($result->title); ?>" title="<?php echo $this->escape($result->title); ?>" />
    		</a>
    	</li>
    	<?php endforeach; ?>
    </ul>
    
    <div class="clearfix"></div>
    <?php endif; ?>
</div>
