<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5264 2010-08-31 10:27:46Z huuphuoc $
 * @since		2.0.2
 */
?>
<div class="t_menu_menu" style="display: none">
	<?php echo $this->navigation()->menu()->renderMenu($this->container, array('ulClass' => 'menu')); ?>
</div>
<div class="clearfix"></div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function() {
	$('.t_menu_menu ul.menu > li').each(function() {
		if ($(this).children('ul').length > 0) {
			var ul  = $(this).children('ul');
			var div = $('<div class="sub"><div class="row"></div></div>').html(ul);
			$(this).append($(div));
		}
	});
	
	$('.t_menu_menu').show();

	$('.t_menu_menu ul.menu li.sub').css({'opacity': '0'});
	$('.t_menu_menu ul.menu li').hoverIntent({    
		sensitivity: 2,
		interval: 100,
		over: megaHoverOver,    
		timeout: 200,
		out: megaHoverOut
	});
});
<?php $this->headScript()->captureEnd(); ?>
