<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5266 2010-08-31 11:25:20Z huuphuoc $
 * @since		2.0.8
 */
?>
<?php if ($this->links) : ?>
<div class="t_core_localeswitcher">
	<?php foreach ($this->links as $locale => $details) : ?>
	<span>
		<a href="<?php echo $details['href']; ?>">
		<?php if ('full' == $this->type) : ?>
			<img src="<?php echo $this->APP_STATIC_SERVER; ?>/images/flags/<?php echo $locale; ?>.png" /> <?php echo $details['localName']; ?>
		<?php elseif ('language' == $this->type) : ?>
			<?php echo $details['localName']; ?>
		<?php else : ?>
			<img src="<?php echo $this->APP_STATIC_SERVER; ?>/images/flags/<?php echo $locale; ?>.png" />
		<?php endif; ?>
		</a>
	</span>
	<?php endforeach; ?>
</div>
<?php endif; ?>
