<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 5365 2010-09-09 15:25:17Z huuphuoc $
 * @since		2.0.7
 */
?>
<div>
	<div class="t_a_bottom"><?php echo $this->translator()->widget('config_select_page'); ?></div>
	<div class="t_a_bottom">
		<select name="page_id" class="t_widget_input">
			<?php foreach ($this->pages as $page) : ?>
			<option value="<?php echo $page->page_id; ?>"><?php echo str_repeat('---', $page->depth) . $page->name; ?></option>
			<?php endforeach; ?>
		</select>
	</div>
	
	<div class="t_a_bottom">
		<input type="checkbox" class="t_widget_input_global" name="global_page_id" /> <?php echo $this->translator()->widget('config_page_from_request'); ?>
	</div>
	
	<hr />
</div>
