<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: set.phtml 5152 2010-08-30 07:25:57Z huuphuoc $
 * @since		2.0.2
 */
?>
<?php 
$this->headTitle(sprintf($this->translator('tag_list_by_tag'), $this->tag->tag_text));
?>

<div class="t_multimedia_set_details">
	<h2><?php echo sprintf($this->translator('tag_list_by_tag'), $this->tag->tag_text); ?></h2>
	
	<?php if ($this->sets) : ?>
	<?php foreach ($this->sets as $index => $set) : ?>
		<?php if ($index % 3 == 0) : ?><ul class="clearfix"><?php endif; ?>
		
		<li>
			<a href="<?php echo $this->url($set->getProperties(), 'multimedia_set_details'); ?>">
				<img src="<?php echo $set->image_small; ?>" />
			</a>
			<h3><?php echo $set->title; ?></h3>
			<cite><?php echo $set->created_date; ?></cite>
			<div><?php echo $set->description; ?></div>
		</li>
		
		<?php if ($index % 3 == 2 || $index == count($this->sets) - 1) : ?></ul><?php endif; ?>
	<?php endforeach; ?>
	<?php endif; ?>
	
	<div class="paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
</div>
