<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: details.phtml 1283 2010-02-24 03:45:15Z huuphuoc $
 * @since		2.0.4
 */
?>
<?php if ($this->revision != null) : ?>
<?php
$this->headTitle($this->revision->title);
?>

<div class="t_news_details t_g_bottom">
	<?php if ($this->revision->sub_title) : ?>
	<h2><?php echo $this->revision->sub_title; ?></h2>
	<?php endif; ?>
	
	<h2><?php echo $this->revision->title; ?></h2>
	<span><?php echo date($this->globalConfig('web')->datetime->format->datetime, strtotime($this->revision->created_date)); ?></span>
	<br />
	<br />
	
	<p><b><?php echo $this->revision->description; ?></b></p>
	
	<div id="t_news_revision_container">
		<?php echo $this->revision->content; ?>
	</div>
	
	<div><b><?php echo $this->revision->author; ?></b></div>
</div>
<?php endif; ?>
