<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5119 2010-08-30 03:28:31Z huuphuoc $
 * @since		2.0.0
 */
?>
<div class="t_utility_countdown">
    <h2><?php echo sprintf($this->translator()->widget('remaining_days'), $this->event); ?></h2>
    
    <div class="content"></div>
    <div class="clearfix"></div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('.t_utility_countdown .content').countdown({ 
		until: new Date(
			<?php echo $this->target['year']; ?>, 
			<?php echo $this->target['mon']; ?> - 1, 
			<?php echo $this->target['mday']; ?>,
			<?php echo $this->target['hours']; ?>,
			<?php echo $this->target['minutes']; ?>,
			<?php echo $this->target['seconds']; ?>		
		)
	});
});
</script>
