<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5234 2010-08-31 06:34:22Z huuphuoc $
 * @since		2.0.2
 */
?>
<?php if ($this->sets) : ?>
<div class="t_multimedia_sets">
    <h2><?php echo $this->translator()->widget('title'); ?></h2>
    	
    <ul>
    	<?php foreach ($this->sets as $set) : ?>
    	<li>
    		<a href="<?php echo $this->url($set->getProperties(), 'multimedia_set_details'); ?>">
    			<img src="<?php echo $set->image_square; ?>" />
    		</a>
    	</li>
    	<?php endforeach; ?>
    </ul>
    
    <div class="clearfix"></div>
</div>
<?php endif; ?>

