<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: _filter.phtml 4127 2010-07-30 07:25:47Z huuphuoc $
 * @since		2.0.0
 */
?>
<?php if (count($this->users) == 0) : ?>
	<?php echo $this->translator('user_list_not_found'); ?>	
<?php else : ?>
<?php foreach ($this->users as $user) : ?>
<div class="clearfix t_a_ui_data_list_content">
	<div class="grid_8 alpha">
		<div><?php echo $user->user_name; ?></div>
		
		<div class="t_a_top t_a_ui_helper_action">
			<a href="<?php echo $this->url(array('user_id' => $user->user_id), 'core_user_edit'); ?>"><?php echo $this->translator('user_list_action_edit'); ?></a> | 
			
			<a href="<?php echo $this->url(array('user_id' => $user->user_id), 'core_rule_set_user'); ?>"><?php echo $this->translator('user_list_action_rule'); ?></a>
			
			<?php if ($user->user_name != $this->currentUser) : ?>
			| <a class="activateAction" rel="<?php echo $user->user_id; ?>_<?php echo (int)$user->is_active; ?>_<?php echo $user->user_name; ?>" href="javascript: void(0);" onclick="javascript: activateUser(this);"><?php if ($user->is_active) : ?><?php echo $this->translator('user_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('user_list_action_activate'); ?><?php endif; ?></a>
			<?php endif; ?>
		</div>
	</div>

	<div class="grid_3"><?php echo $user->email; ?></div>
	
	<div class="grid_1 omega"><?php echo $user->user_id; ?></div>
</div>
<?php endforeach; ?>

<div class="t_a_bottom t_a_ui_paginator">
	<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
</div>
<?php endif; ?>
