<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5394 2010-09-12 16:05:40Z huuphuoc $
 * @since		2.0.9
 */
?>
<div class="t_utility_whoisonline">
	<h2><?php echo $this->translator()->widget('title'); ?></h2>
	
	<div><?php echo sprintf($this->translator()->widget('users_online'), $this->total, $this->numUsers, $this->numGuests); ?></div>
	<?php if ($this->users) : ?>
	<div>
		<?php echo $this->translator()->widget('registered_users_online'); ?>
		<?php foreach ($this->users as $index => $user) : ?>
		<?php if ($index > 0) : ?>, <?php endif; ?><span><?php echo $user->user_name; ?></span>
		<?php endforeach; ?>
	</div>
	<?php endif; ?>
</div>
