<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: complete.phtml 3858 2010-07-22 04:49:00Z huuphuoc $
 * @since		2.0.1
 */
?>
<?php 
$this->headTitle($this->translator('install_complete_page_title'));
?>

<div class="t_a_install_step">
	<ul>
		<li class="grid_3 alpha">
			<span>1</span>		
			<h2><?php echo $this->translator('install_steps_language'); ?></h2>
		</li>
		<li class="grid_3">
			<span>2</span>		
			<h2><?php echo $this->translator('install_steps_requirements'); ?></h2>
		</li>
		<li class="grid_3">
			<span>3</span>		
			<h2><?php echo $this->translator('install_steps_config'); ?></h2>
		</li>
		<li class="t_a_install_step_active grid_3 omega">
			<span>4</span>
			<h2><?php echo $this->translator('install_steps_complete'); ?></h2>
		</li>
	</ul>
</div>

<div class="t_a_install_container">
	<div class="grid_12 t_a_top">
	<form method="post" action="<?php echo $this->url(array(), 'core_install_complete'); ?>">
		<h3><?php echo $this->translator('install_complete_complete'); ?></h3>
		<hr />
		
		<div class="t_a_bottom">
			<?php echo $this->translator('install_complete_installed_success'); ?><br /><br />
			<?php echo $this->translator('install_complete_guide'); ?><br />
			- <?php echo $this->translator('install_complete_admin_username'); ?>: admin<br />
			- <?php echo $this->translator('install_complete_admin_password'); ?>: <span class="t_a_ui_helper_message"><?php echo $this->password; ?></span><br />
			<br />
			<?php echo sprintf($this->translator('install_complete_change_password'), $this->url.'/admin/'); ?>
		</div>
		
		<div class="prefix_2 suffix_2" style="text-align: center">
			<div class="grid_8 t_a_bottom">
				<b><?php echo $this->translator('install_complete_press_button_message'); ?></b>
			</div>
			
			<div class="grid_8 t_a_bottom">
				<div class="alpha grid_3 t_a_textright" style="margin-top: 20px">
					<button type="submit" name="gotoFrontend" value="gotoFrontend"><span><?php echo $this->translator('install_complete_go_to_frontend'); ?></span></button>
				</div>
				
				<div class="grid_1">
					<div class="t_a_ui_helper_line_ver">
						<div><?php echo $this->translator('install_complete_or'); ?></div>
						<div></div>
					</div>
				</div>
				
				<div class="omega grid_4 t_a_textleft" style="margin-top: 20px">
					<button type="submit" name="gotoBackend" value="gotoBackend"><span><?php echo $this->translator('install_complete_go_to_backtend'); ?></span></button>
				</div>
			</div>
		</div>
	</form>
	</div>
</div>
