<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: default.phtml 5165 2010-08-30 08:36:44Z huuphuoc $
 * @since		2.0.0
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->CHARSET; ?>" />
    <meta name="viewport" content="width=device-width, height=device-height" />
    <meta name="robots" content="noindex, nofollow" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skins/mobile/default/default.css" />
	<script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery/jquery.min.js"></script>
	<?php echo $this->headTitle(); ?>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<?php echo $this->render('_header.phtml'); ?>
		</div>
		
		<div id="container">
			<?php echo $this->layoutLoader(); ?>
			<div class="clearfix"></div>
		</div>
		
		<div id="footer">
			<?php echo $this->render('_footer.phtml'); ?>
		</div>
	</div>
</body>
</html>	
