<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 5369 2010-09-09 16:09:14Z huuphuoc $
 * @since		2.0.8
 */
?>
<div>
	<div class="t_a_bottom"><?php echo $this->translator()->widget('config_select_size'); ?></div>
	<div class="t_a_bottom">
		<select name="size" class="t_widget_input">
			<option value="default"><?php echo $this->translator()->widget('config_default_size'); ?></option>
			<option value="compact"><?php echo $this->translator()->widget('config_compact_size'); ?></option>
		</select>
	</div>
	
	<hr />
</div>
