<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5223 2010-08-31 01:58:18Z huuphuoc $
 * @since		2.0.0
 */
?>
<div class="t_utility_socialshare">
	<ul>
		<?php if ('default' == $this->size) : ?>
		<li class="share"><a name="fb_share" type="box_count"></a></li>
		<li class="share"><a href="http://twitter.com/share" class="twitter-share-button" data-count="vertical">Tweet</a></li>
		<li class="share"><a class="DiggThisButton DiggMedium"></a></li>
		<?php elseif ('compact' == $this->size) : ?>
		<li class="share"><a name="fb_share" type="button_count"></a></li>
		<li class="share"><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a></li>
		<li class="share"><a class="DiggThisButton DiggCompact"></a></li>
		<?php endif; ?>
		<li class="clearfix"></li>
	</ul>
</div>
