<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 5116 2010-08-30 03:16:31Z huuphuoc $
 * @since		2.0.3
 */
?>
<?php if ($this->username) : ?>
<div class="t_comment_disqus">
	<h2><?php echo $this->translator()->widget('title'); ?></h2>

	<div id="disqus_thread"></div>
	<script type="text/javascript" src="http://disqus.com/forums/<?php echo $this->username; ?>/embed.js"></script>
	<noscript><a href="http://disqus.com/forums/<?php echo $this->username; ?>/?url=ref">View the discussion thread.</a></noscript>
	<a href="http://disqus.com" class="dsq-brlink"><?php echo $this->translator()->widget('powered_by'); ?></a>
</div>
<?php endif; ?>
