<?php
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: reset.phtml 3373 2010-06-29 07:53:17Z huuphuoc $
 * @since		2.0.6
 */
?>
<?php
$this->headTitle($this->translator('auth_reset_page_title'));
?>

<div class="grid_8 prefix_2 suffix_2">
	<h1>TomatoCMS</h1>
	
	<div class="alpha grid_4 prefix_2">
		<?php if ($this->invalidLink) : ?>
		<div class="t_a_message_warning"><?php echo $this->translator('auth_reset_invalid_link'); ?></div>
		<?php else : ?>
		<div class="t_a_message"><?php echo $this->translator('auth_reset_sent_mail'); ?></div>
		<?php endif; ?>
	</div>
</div>
